(eval-when (:compile-toplevel :load-toplevel)(FOIL::ENSURE-PACKAGE "System")
(FOIL::ENSURE-PACKAGE "System.ComponentModel")
)(DEFCONSTANT |System.ComponentModel|::COMPMODSWITCHES. (QUOTE |System.ComponentModel|::|CompModSwitches|))
(DEFCLASS |System.ComponentModel|::COMPMODSWITCHES. (|System|:OBJECT.) NIL)
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.NEW (&REST FOIL::ARGS) "Void .ctor()
" (FOIL::CALL-CTOR (QUOTE |System.ComponentModel|::|CompModSwitches|) FOIL::ARGS))
(DEFMETHOD MAKE-NEW ((FOIL::CLASS-SYM (EQL (QUOTE |System.ComponentModel|::|CompModSwitches|))) &REST FOIL::ARGS) (APPLY (FUNCTION |System.ComponentModel|::COMPMODSWITCHES.NEW) FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_EXPRPARSER (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_ExprParser()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_ExprParser" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_EXPRPARSER) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_BINARYNODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_BinaryNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_BinaryNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_BINARYNODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_NAMENODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_NameNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_NameNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_NAMENODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_CONSTNODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_ConstNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_ConstNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_CONSTNODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_DATAEXPRESSION (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_DataExpression()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_DataExpression" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_DATAEXPRESSION) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_SORTS (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_Sorts()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_Data_Sorts" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_SORTS) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_DATAVIEW (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_DataView()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_DataView" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_DATAVIEW) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.TOSTRING (FOIL::THIS &REST FOIL::ARGS) "System.String ToString()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "ToString" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.TOSTRING) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_LOOKUPNODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_LookupNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_LookupNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_LOOKUPNODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.EQUALS (FOIL::THIS &REST FOIL::ARGS) "Boolean Equals(System.Object)
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "Equals" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.EQUALS) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_FUNCTIONNODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_FunctionNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_FunctionNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_FUNCTIONNODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_AGGREGATENODE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_AggregateNode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_AggregateNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_AGGREGATENODE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GETTYPE (FOIL::THIS &REST FOIL::ARGS) "System.Type GetType()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "GetType" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GETTYPE) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GETHASHCODE (FOIL::THIS &REST FOIL::ARGS) "Int32 GetHashCode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "GetHashCode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GETHASHCODE) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_CONSTRAINTS (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_Constraints()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_Data_Constraints" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_CONSTRAINTS) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_COLUMNCHANGE (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_ColumnChange()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_Data_ColumnChange" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_COLUMNCHANGE) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.GET_XMLWRITER (&REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_XmlWriter()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CompModSwitches|) "get_XmlWriter" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.GET_XMLWRITER) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.DATA_SORTS (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_Sorts()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "Data_Sorts" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.DATA_SORTS-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.NAMENODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_NameNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "NameNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.NAMENODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.LOOKUPNODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_LookupNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "LookupNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.LOOKUPNODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.AGGREGATENODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_AggregateNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "AggregateNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.AGGREGATENODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.CONSTNODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_ConstNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "ConstNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.CONSTNODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.FUNCTIONNODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_FunctionNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "FunctionNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.FUNCTIONNODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.DATAEXPRESSION (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_DataExpression()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "DataExpression" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.DATAEXPRESSION-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.BINARYNODE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_BinaryNode()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "BinaryNode" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.BINARYNODE-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.XMLWRITER (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_XmlWriter()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "XmlWriter" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.XMLWRITER-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.DATAVIEW (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_DataView()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "DataView" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.DATAVIEW-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.DATA_CONSTRAINTS (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_Constraints()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "Data_Constraints" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.DATA_CONSTRAINTS-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.EXPRPARSER (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_ExprParser()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "ExprParser" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.EXPRPARSER-GET) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::COMPMODSWITCHES.DATA_COLUMNCHANGE (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.TraceSwitch get_Data_ColumnChange()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CompModSwitches|) "Data_ColumnChange" (QUOTE |System.ComponentModel|::COMPMODSWITCHES.DATA_COLUMNCHANGE-GET) FOIL::THIS FOIL::ARGS))
(DEFCONSTANT |System.ComponentModel|::CORESWITCHES. (QUOTE |System.ComponentModel|::|CoreSwitches|))
(DEFCLASS |System.ComponentModel|::CORESWITCHES. (|System|:OBJECT.) NIL)
(DEFUN |System.ComponentModel|::CORESWITCHES.NEW (&REST FOIL::ARGS) "Void .ctor()
" (FOIL::CALL-CTOR (QUOTE |System.ComponentModel|::|CoreSwitches|) FOIL::ARGS))
(DEFMETHOD MAKE-NEW ((FOIL::CLASS-SYM (EQL (QUOTE |System.ComponentModel|::|CoreSwitches|))) &REST FOIL::ARGS) (APPLY (FUNCTION |System.ComponentModel|::CORESWITCHES.NEW) FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.TOSTRING (FOIL::THIS &REST FOIL::ARGS) "System.String ToString()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CoreSwitches|) "ToString" (QUOTE |System.ComponentModel|::CORESWITCHES.TOSTRING) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.EQUALS (FOIL::THIS &REST FOIL::ARGS) "Boolean Equals(System.Object)
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CoreSwitches|) "Equals" (QUOTE |System.ComponentModel|::CORESWITCHES.EQUALS) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.GETTYPE (FOIL::THIS &REST FOIL::ARGS) "System.Type GetType()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CoreSwitches|) "GetType" (QUOTE |System.ComponentModel|::CORESWITCHES.GETTYPE) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.GETHASHCODE (FOIL::THIS &REST FOIL::ARGS) "Int32 GetHashCode()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CoreSwitches|) "GetHashCode" (QUOTE |System.ComponentModel|::CORESWITCHES.GETHASHCODE) FOIL::THIS FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.GET_PERFTRACK (&REST FOIL::ARGS) "System.Diagnostics.BooleanSwitch get_PerfTrack()
" (FOIL::FOIL-CALL-METHOD (QUOTE |System.ComponentModel|::|CoreSwitches|) "get_PerfTrack" (QUOTE |System.ComponentModel|::CORESWITCHES.GET_PERFTRACK) NIL FOIL::ARGS))
(DEFUN |System.ComponentModel|::CORESWITCHES.PERFTRACK (FOIL::THIS &REST FOIL::ARGS) "System.Diagnostics.BooleanSwitch get_PerfTrack()
" (FOIL::CALL-PROP-GET (QUOTE |System.ComponentModel|::|CoreSwitches|) "PerfTrack" (QUOTE |System.ComponentModel|::CORESWITCHES.PERFTRACK-GET) FOIL::THIS FOIL::ARGS))
(eval-when (:compile-toplevel :load-toplevel)
(export '(|System.ComponentModel|::CORESWITCHES.PERFTRACK |System.ComponentModel|::CORESWITCHES.GET_PERFTRACK |System.ComponentModel|::CORESWITCHES.GETHASHCODE |System.ComponentModel|::CORESWITCHES.GETTYPE |System.ComponentModel|::CORESWITCHES.EQUALS |System.ComponentModel|::CORESWITCHES.TOSTRING |System.ComponentModel|::CORESWITCHES.NEW |System.ComponentModel|::CORESWITCHES. |System.ComponentModel|::COMPMODSWITCHES.DATA_COLUMNCHANGE |System.ComponentModel|::COMPMODSWITCHES.EXPRPARSER |System.ComponentModel|::COMPMODSWITCHES.DATA_CONSTRAINTS |System.ComponentModel|::COMPMODSWITCHES.DATAVIEW |System.ComponentModel|::COMPMODSWITCHES.XMLWRITER |System.ComponentModel|::COMPMODSWITCHES.BINARYNODE |System.ComponentModel|::COMPMODSWITCHES.DATAEXPRESSION |System.ComponentModel|::COMPMODSWITCHES.FUNCTIONNODE |System.ComponentModel|::COMPMODSWITCHES.CONSTNODE |System.ComponentModel|::COMPMODSWITCHES.AGGREGATENODE |System.ComponentModel|::COMPMODSWITCHES.LOOKUPNODE |System.ComponentModel|::COMPMODSWITCHES.NAMENODE |System.ComponentModel|::COMPMODSWITCHES.DATA_SORTS |System.ComponentModel|::COMPMODSWITCHES.GET_XMLWRITER |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_COLUMNCHANGE |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_CONSTRAINTS |System.ComponentModel|::COMPMODSWITCHES.GETHASHCODE |System.ComponentModel|::COMPMODSWITCHES.GETTYPE |System.ComponentModel|::COMPMODSWITCHES.GET_AGGREGATENODE |System.ComponentModel|::COMPMODSWITCHES.GET_FUNCTIONNODE |System.ComponentModel|::COMPMODSWITCHES.EQUALS |System.ComponentModel|::COMPMODSWITCHES.GET_LOOKUPNODE |System.ComponentModel|::COMPMODSWITCHES.TOSTRING |System.ComponentModel|::COMPMODSWITCHES.GET_DATAVIEW |System.ComponentModel|::COMPMODSWITCHES.GET_DATA_SORTS |System.ComponentModel|::COMPMODSWITCHES.GET_DATAEXPRESSION |System.ComponentModel|::COMPMODSWITCHES.GET_CONSTNODE |System.ComponentModel|::COMPMODSWITCHES.GET_NAMENODE |System.ComponentModel|::COMPMODSWITCHES.GET_BINARYNODE |System.ComponentModel|::COMPMODSWITCHES.GET_EXPRPARSER |System.ComponentModel|::COMPMODSWITCHES.NEW |System.ComponentModel|::COMPMODSWITCHES.) "System.ComponentModel")
)
